const actions = {
	UPDATE_USER: 'UPDATE_USER',
	UPDATE_WALLET: 'UPDATE_WALLET',
	CREATE_WALLET: 'CREATE_WALLET',
	UPDATE_SETTINGS: 'UPDATE_SETTINGS',
	UPDATE_OMNIBOLT: 'UPDATE_OMNIBOLT',
	UPDATE_LIGHTNING: 'UPDATE_LIGHTNING',
};
export default actions;
