name: Bug Report
description: Create a report to help us improve
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: The bug happened when I opened the app...
    validations:
      required: true
  - type: textarea
    id: reproduce-bug
    attributes:
      label: Reproduce
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Recording
      description: If applicable, add screenshots or a video recording to help explain your problem.
    validations:
      required: false
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system (OS) and version is Bitkit running on?
      placeholder: e.g. Android 12, iOS 16
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Bitkit version
      description: What version of Bitkit were you running when the bug occurred? You can find the version number on the About page.
      placeholder: e.g. v1.0.0
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
